name: Deploy my app on vps

on:
  push:
    branches: 
      - main
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/abhit2511/ipuranks/backend
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            git reset --hard
            git pull origin main
            npm install
            npx tsc -b
            pm2 reload ecosystem.config.cjs